services:
  - type: web
    name: save-the-date-wedding
    env: static
    buildCommand: echo "No build required"
    staticPublishPath: .
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
